language: node_js
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get -y --force-yes install rethinkdb
before_script:
  - export CHROME_BIN=chromium-browser
  - export NODE_ENV=travis
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rethinkdb --daemon
node_js:
  - "4"
  - "5"